### ISSUE TITLE
Set up a production environment so that the webclient can be deployed

### ISSUE THREAD

**Issue by aneeshd16** [loklak/loklak_webclient#114]
Since, we now also use a node server, deploying just the `build` directory won't do.
Running the node server independently (without `gulp dev`) shows a ENOENT error, as it now has a different root path. I have two possible solutions:
a. `gulp prod` should copy all files within the `server` directory to a `deploy` directory and the frontend code is generated in `deploy/build` directory. This separates deployment files from development files. However, copying of the `server/node_modules` directory will take an unreasonable amount of time. Directory structure:
````
/root
  deploy/
     build/
        index.html (frontend files)
        .
     index.js (Server files)
     .
     .
````
b. `gulp prod` generates the `build` folder inside the `server` folder instead of generating it at the root folder. The `server` directory can then be deployed. This would result in the mixing of deployment and development files. However, this seems to be the best solution now. 
````
/root
  server/
     build/
        index.html (frontend files)
        .
     index.js (Server files)
     .
     .
````

@loklak/loklak_developers what do you think?

**Comment by Orbiter** [comment]
Good that you open this issue. What I want to do is:
- not care about a branch. I want to deploy the main branch automatically, so please shift into main whatever is safe to run.
- I want to make your progress visible, even if it's incomplete or not functional at that time. If the function is a stub and not working, just write on it 'this is a stub, not working yet' (in the interface) so everybody knows that this is a construction place.

**Comment by sudheesh001** [comment]
I think using github deployment hooks https://developer.github.com/guides/delivering-deployments/ is the best way, but this means the following 

#### Advantages
1. One time setup to the server from the master branch
2. Easy to put up a few setup scripts so that the shell file / deployment script can automatically do all its operations and do the required setup of the new code on the server
3. Secure server and only one person needs to know the credentials of the server instead of the whole team.

#### Disadvantages
1. Need more careful review of the patches and all have to come through pull requests so that the production server doesn't break with the changes made
2. Any mistakes made need to be manually reverted on the server and re run.

**Comment by fuksi** [comment]
I'd like to emphasize that no matter what the process is, the node server will be restarted very server related deployment. But an automation script could not determine itself, if the patch is server related. For e.g. if I just push some css change, it shouldn't do ```npm install; node server.js..``` 

I suggest moving the node server to a submodule, then it is ran/deployed separately. And the automation script would be very simple for the server submodule.

Current ```gulp deploy``` is still a manual process. To automate it, we can:
1. Define here a ```server_config.json``` that works for the production server.
2. Define a task a add ```<base href="/server_sudirectory"/>``` to index.html

I believe this approach will make the setup for @sudheesh001 suggestion easier.

**Comment by aneeshd16** [comment]
This article looks to be helpful
http://seanvbaker.com/using-git-to-deploy-node-js-sites-on-ubuntu/

**Comment by Orbiter** [comment]
temporary assigned to @aneeshd16 .. please rotate each 2 weeks

**Comment by aneeshd16** [comment]
Here is my deploy.sh
````
cd loklak_webclient
pm2 stop index
git pull origin master
sudo npm install
cd server
sudo npm install
cd ..
sudo gulp prod
sudo pm2 start server/index.js
````
pm2 works perfectly fine for me. However, I suggest manually starting this script instead of automating it with github webhooks.
Reason: `gulp prod` fails sometimes (due to race conditions, I think), but completes successfully after retrying. If something can be developed that automatically retries `gulp prod` on errors, that would be excellent.

**Comment by Orbiter** [comment]
good hint to use pm2! However, I would like to see code changes in main as soon as possible in test.loklak.net so everybody can see what is happening without wasting time to deploy their own main in that moment. If it is not too complex to create automated deployment on test.loklak.net, please do.

**Comment by aneeshd16** [comment]
This is more or less the same as #158. Can we close this?

**Comment by sudheesh001** [comment]
@aneeshd16 We're sticking to the `screen` services to run forever rather than using pm2, makes the application have one less dependency.
As mentioned in https://github.com/loklak/loklak_webclient/issues/158#issuecomment-112879801 , the only thing we need to do is properly name our screen sessions. That'd make it easier for others to easily deploy.

I'll write a noob's intro to screen as a seperate file `Production.md` so that we can close this issue with the correct documentation of how to put the app into production. Our Readme file is getting cluttered with a lot of content. So its time to break it into the documents we need to do.

**Comment by aneeshd16** [comment]
@sudheesh001 , pm2 will automatically do two things:
1. Clustering. Automatically makes use of the multiple cores on the system
2. Automatic restarting of the app if it crashes.

I don't know if `screen` does that, but my experience with pm2 has been very positive.
