### ISSUE TITLE
Create a modal for creating a new tweet.

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#118]
- Create a button to create a new tweet
- When click on button, pop up a modal (like tweet-modal) with a form to submit a new tweet.

**Comment by sudheesh001** [comment]
Fixed via #179

**Comment by Orbiter** [comment]
The tweet button is not working in Firefox.
This is also not finished at all! Have a look to the original 'New Tweet' window:
![newtweet](https://cloud.githubusercontent.com/assets/238730/8149912/14095202-12d6-11e5-9f32-e1716d42127a.png)
- the window is floating
- you can add attachments (Pictures, for us also: also Loction, Text, Audio, Video)
Thats what is expected here!

**Comment by sudheesh001** [comment]
@Orbiter The aim of this issue was to get the Tweet modal up, https://github.com/loklak/loklak_webclient/issues/166 focuses on the finer details like the photo attachments and locations. I've commented there too. 

Since we're on a design change I don't really mind if this issue is left open.

**Comment by mariobehling** [comment]
For new functionality, please offer a link to a place, where can we test this? It is also advisable to add a screenshot of new visual features.

**Comment by sudheesh001** [comment]
Tweet interface with the new file picker option as a button instead of the usual file picker.
![screen shot 2015-07-01 at 9 58 44 pm](https://cloud.githubusercontent.com/assets/4545925/8459683/8a4c9e38-203c-11e5-88d0-d4bfa33177a5.png)
Action post clicking on the Add Image button.
![screen shot 2015-07-01 at 10 00 02 pm](https://cloud.githubusercontent.com/assets/4545925/8459684/8d2c2e66-203c-11e5-928c-fd274179513d.png)
My VM seems to be down for some reason, I am looking into that to see what has happened.
