### ISSUE TITLE
Conversations in search view

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#122]
From twitter search, you can browse the conversation and reply to a certain tweet in the conversation.
Technically they are not 'replies', they are just tweet, that mention at least the OP and related to a certain tweet. 

With only status ID, I can't yet evaluate the relations between tweets to make a conversation.
@Orbiter what do you think?

Quick example: https://twitter.com/codinghorror/status/606680573625696256
![image](https://cloud.githubusercontent.com/assets/6878677/8019303/2a06af50-0c50-11e5-9b63-dc72c41464c8.png)

**Comment by sudheesh001** [comment]
:+1:

**Comment by Orbiter** [comment]
right now I don't have a data structure ready to have references for the conversation. The only option I see right now is, to simulate a conversation history by just doing a query for the name of the conversation starter, like here: search for @codinghorror and restrict it with from:<date> to the date of the conversation starter and with until:<date> to a date not more than 24h after the conversation startet. Furthermore, the query must be done with source=cache because otherwise the query goes to the scraper and twitter does not understand since and until.

Example:
http://localhost:9100/api/search.json?timezoneOffset=-120&q=%40codinghorror+since%3A2015-06-05+until%3A2015-06-06&source=cache

**Comment by fuksi** [comment]
I can't go with this hack now, because

- In a search result, a particular user tends to appear again and again as he/she posts tweet regularly. 24h would mix up things
- Some reply start with @codinghorror, some are just mentioning him in a totally separated tweet, and then there are also RT.

I set this as low priority since default search result doesn't show conversation as the moment, unless the user is curious enough.

**Comment by Orbiter** [comment]
I can follow your criticism, however I cannot see any other way to go unless we use the twitter api to retrieve the 'real' conversation. I will investigate a way to identify conversation details from the scraper and also to add a field for a conversation history. Maybe also a different query constraint or modifier is necessary.
Related issues in loklak_server: https://github.com/loklak/loklak_server/issues/49 and https://github.com/loklak/loklak_server/issues/50

**Comment by mariobehling** [comment]
We need to adapt to new implementations of conversation views and discuss this in a new issue as things have changed.
