### ISSUE TITLE
npm warnings in fresh clone

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#150]
I deleted my local clone of loklak_webclient and cloned it again.
I also deleted my ~/.npm files to get a fresh start.
 Then I started ```npm install```in loklkal_webclient home path and got:
```
npm WARN peerDependencies The peer dependency istanbul@~0.3.0 included from karma-coverage will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN optional dep failed, continuing fsevents@0.3.6
npm WARN optional dep failed, continuing fsevents@0.3.6
npm WARN optional dep failed, continuing fsevents@0.3.6
```
This process should start without warnings.
Question: is this related to node or is it related to loklak?
- If this is related to node and cannot be supressed, close this issue.
- if this is related to loklak, remove the question tag and move on working on this as a bug issue.

**Comment by prasht63** [comment]
I suggest we discuss once what all packages we are using right now for our web client.There are many node modules which came with the boiler plates which are outdated(I guess the boilerplate has not been updated) and cause conflicting dependencies.As stated in #142 .
As of this I think this is due to node cause I could not reproduce it on my system.
@aneeshd16 @sudheesh001 @fuksi Lets discuss a time when we can work on #142

**Comment by aneeshd16** [comment]
istanbul is a code coverage reporter. Not required as of now. Although it would be a good idea to write tests in the future.
Agree with @prasht63 .

**Comment by Orbiter** [comment]
@prasht63 as you closed this, the answer to the question is "this is related to node and cannot be supressed". correct? If not, reopen this issue as bug and remove the 'question' tag.
