### ISSUE TITLE
Use angular to render the /account page instead of node ejs

### ISSUE THREAD

**Issue by aneeshd16** [loklak/loklak_webclient#155]
When the user logs in, the user is navigated to `/account`. This page is rendered by the node ejs engine which renders `server/views/index.ejs`. This page is separate from our angular application and thus needs to be updated separately when we update the design of our app.

### Proposal
* Make a new route in angular for `/account`
* Define an angular service that should be able to detect if a user is logged in or not.
* This service can be accessed throughout the app and can be used to render pages accordingly

@sudheesh001 @fuksi @prasht63

**Comment by sudheesh001** [comment]
Doing this would still suppot `ejs` right ? Breaking that would cause serious issues and lots of extra computation from our side to keep the elements in the right places.

**Comment by aneeshd16** [comment]
@sudheesh001 see #157

**Comment by sudheesh001** [comment]
@aneeshd16 Is this still related ? the /account used to be the place the tweet functionality used to work from, #92 reference solves that problem because now we don't need a specific route to tweet but rather the tweet functionality is present in everypage as its integrated with the lightbox modal that appears from top nav bar. If this is what is the required functionality, I believe this bug is good to close.

**Comment by aneeshd16** [comment]
yep, this issue does not make sense now. Closing.
