### ISSUE TITLE
Changing method of authentication. 

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#157]
@loklak/loklak_developers  

I mentioned that I'll implement a client-side auth with hello.js, and here it is.

http://46.101.145.49:3000/

Click signup to login, and it should returns where you are without changing location. And then you'll have a authorized session for a period of time, until you click logout. This session will be also available to the global scope of the angular application (I did a quick example there to show your profile picture and screen name). This solution embraces the current structure of our SPA. And from here all of us can use the session easily in different views.  

With this, we won't have to serve a passport server for auth, which I don't know how it will work exactly in the future, because now, we can only callback to ```/account``` which belong a  the passport module. Then how would we manage a session through out the entire angular application? How can angular access that session?

**To reproduce the live version**
Checkout branch https://github.com/loklak/loklak_webclient/tree/dev-login-hellojs
```npm install```
```cp helloConfig.js.sample helloConfig.js```
Place your consumer key (API key) in there
With your app created on twitter, remember to point website and callback to your url said ```http://myhost.com/```
Since twitter is using Oauthv1 go to https://auth-server.herokuapp.com/
Sign in, add new app, add credentials according to your server. 
![image](https://cloud.githubusercontent.com/assets/6878677/8102421/b20c0770-1028-11e5-85c3-3fecf90d9546.png)
```npm cache clean```
```gulp dev```

Pm me if you need help setting up.

**Comment by aneeshd16** [comment]
Tested, works beautifully. Solves a lot of problems regarding authenticated users since it also maintains a session. It would also resolve #155.
Instead of https://auth-server.herokuapp.com/, we can use https://www.npmjs.com/package/oauth-shim so that we do not have any external dependencies. Advantages/side effects:
* We can have the angular app and auth-server as two different entities.
* The angular app can be served statically.
* Deployment will be as simple as a `git pull` and `gulp prod`.
* The auth server in node will remain constant. If all goes well, no changes will be needed to it ever.

@loklak/loklak_developers kindly give feedback. This is high priority. IMO we should go ahead with this.

**Comment by sudheesh001** [comment]
:+1:

**Comment by aneeshd16** [comment]
Unfortunately, the custom oauth-shim oauth proxy server requires https. If https is not possible on our deployment, then we can go with https://auth-server.herokuapp.com/. However, it is an external dependency and may/may not be reliable.

**Comment by aneeshd16** [comment]
deployed here. http://aneesh-ojl02abl.cloudapp.net:3001/
Please test.

**Comment by fuksi** [comment]
Tested, also works locally as expected.

**Comment by prasht63** [comment]
Tested. Good to go from my side :+1:

**Comment by fuksi** [comment]
It's decided then. Move to merge #164.
