### ISSUE TITLE
Add a separate settings file for social credentials. Add new documentation

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#198]
Remove `twitterConsumerSecrent` from `custom_configFile.json` (and of course from configFile.json), and move it to a new file, e.g. `custom_socialCreds.json`

`Gulp settings` should request from server `api/settings.json` to **UPDATE** the social credentials
- If fields are already there in  `custom_socialCreds.json`, update it with new value from the response result.
- If fields are new, append to ` `custom_socialCreds.json`
- In this way,  `custom_socialCreds.json` is **NEVER EMPTY**, because during setting up from the frontend, user should already initialized the fields. 

Please add documentations accordingly. Currently there is no documentation regarding server settings.

**Comment by Orbiter** [comment]
This is a misunderstanding of https://github.com/loklak/loklak_webclient/commit/92e614caa65a22e31440cdc9c6f49778c7c2fcb9#commitcomment-11745965
There shall not be a separation of credentials and other settings, there shall only be the option that the server may be able to overload the given settings. Therefore this issue is void.
Please work on re-opened https://github.com/loklak/loklak_webclient/issues/172
