### ISSUE TITLE
Implement Connect function for services, IoT and data sources and show them on the loklak map

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#205]
Goal of this project is to be able to display all kinds of data on a map and to tweet it. Some data should only show up in the private user account (e.g. locations of contacts, private calendars). Other data might also be displayed publicly e.g. Internet of Things (think of a weather station on people's balcony).

The map page should show followers/following and tweets of the user and his followers/following in distinctive ways, e.g. with different colors. Also there needs to be a control box to switch on/off the different layers. Any data sources that are added by the user should also show up as a layer here automatically.

For the connect data area, please include the following:

1. Add a "Connect" item to the top navigation bar.
![loklak-connect](https://cloud.githubusercontent.com/assets/1583873/8267598/21b2a66e-1769-11e5-9547-bca5af5092f0.png)

2. Implement lightbox overlay with 
a) Emails, Contacts and Calendar connectors
b) Internet of Things
c) Data Sources
d) Applications

A first UI draft below.
![loklak-connect-services](https://cloud.githubusercontent.com/assets/1583873/8267604/5837635a-1769-11e5-950d-0d2bedd6c019.png)

![loklak-iot-connect-services](https://cloud.githubusercontent.com/assets/1583873/8267605/5e7719b8-1769-11e5-8f19-693ee7d07a73.png)

**Comment by mariobehling** [comment]
Please create a project plan with Milestones and cooperate on getting data into loklak e.g. check out this issue: https://github.com/loklak/loklak_webclient/issues/206

**Comment by mariobehling** [comment]
@prasht63 Please have a look at this project outline again and the information that we added. We have missed to follow up with you on a plan. Your plan is still missing. Please add it for the following milestones. What will you achieve in GSoC? Thank you.

**Comment by prasht63** [comment]
Plan : The plan is divided in coming milestones.Since we have so much data to visualise and not so much time so I have segregated a few data which are more useful, popular and unique.The goal is to visualise data which has not been visualised before in a way that it leaves a impression on the user.Since that is main aim of data visualisation on map, presenting the big picture around the globe on a computer screen.

Milestone : 3
1:Adding Start Ups on World Map by integrating Angel.co and show startups and investors on the map.This will provide the user the ability to geographically see the start-up culture and apply to a start-up based on a geographic filter. Issue https://github.com/loklak/loklak_webclient/issues/226 API Here.

2: Adding and Implementing Campaign Donations on a Map : This is going to be one hot feature of loklak.net where people can see the amount of donations political parties receive for their campaigns.Currently I did not find a comprehensive map showing this data.I plan to show it in state wise way through a chloropleth map.Issue https://github.com/loklak/loklak_webclient/issues/224 [Chloropleth Example] Link API.

3:Integrate sensor data from weather stations, wind temperature and other sensors on the loklak map.The plan is to create a simple script which @wavicles can use to stream the realtime data which can be updated on the map at regular interval.Will need discussions with @wavicles Issue https://github.com/loklak/loklak_webclient/issues/212


Milestone : 4
Weather Forecast about major climatic changes through Tweets : API here Issue https://github.com/loklak/loklak_webclient/issues/223

Instagram photos on the World Map : This will allow the user to view his Instagram Photos on the World Map. More details to be added soon

[Chloropleth Example]: http://leafletjs.com/examples/choropleth.html

**Comment by mariobehling** [comment]
Ok, sounds good. In which milestone will you implement Instagram? I see you linked meetup.com - Great! Also, please link the issue to angel.co.

**Comment by prasht63** [comment]
@mariobehling sure!

**Comment by prasht63** [comment]
Instagram will be done in 4th Milestone

**Comment by mariobehling** [comment]
Ok, great. We have defined some milestone dates. As we go on, please continue to add details to plans until M4.5

 Milestone 3, Due by July 25, 2015
 Milestone 3.5 Sprint, Due by August 12, 2015 
 Milestone 4, Due by August 21, 2015
 Milestone 4.5, Due by August 31, 2015

**Comment by mariobehling** [comment]
@prasht63 I hope this helps you to get a better sense of direction: I have updated the list of features for milestone. Does M3 work for you? Also, please check the ongoing tasks. For the following milestones we can add more details as we proceed.

Can you pledge that you will finish the tasks of M3, please?

**Comment by Orbiter** [comment]
please retrieve the follower list from loklak_server, documentation is online at http://loklak.org/api.html#account .. please scroll down to "Retrieval of Twitter User Account Data" for details
