### ISSUE TITLE
Integrate Angel.co and show startups and investors on a map

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#225]
All details for the API are here: https://angel.co/api

**Comment by mariobehling** [comment]
As you discussed in the milestone umbrella issue, this feature is important to be implemented as a showcase for M3. https://github.com/loklak/loklak_webclient/issues/205#issuecomment-120116543

**Comment by mariobehling** [comment]
Are you clear about the flow for the user? The goal is that the user can add Angel.co Api-Data to his map. User actions to include e.g.:
1. Add data source in "connect" area
2. Automatically create layer for Angel.co on map

![screenshot from 2015-07-15 09 40 05](https://cloud.githubusercontent.com/assets/1583873/8693216/d06dcdd0-2ad5-11e5-81c5-79bf3492eda5.png)

**Comment by prasht63** [comment]
Yes Mario I am thinking on the same terms.I will add a mock up in a couple
of hours, once I finish putting up the number of followers.

**Comment by Orbiter** [comment]
please retrieve the follower list from loklak_server, documentation is online at http://loklak.org/api.html#account .. please scroll down to "Retrieval of Twitter User Account Data" for details

**Comment by prasht63** [comment]
@fuksi I am trying to implement Angel.co authorisation via their oAuth server.Guidelines here https://angel.co/api/oauth/faq . I get the code from the first step then I send a post request as they have said, to which I get a response status of 0. The code is in https://github.com/loklak/loklak_webclient/tree/Angel-oAuth branch. Ways to test . go to data connect, click on the link Angel.co and see console
currently the code shows client secret that will be changed and will be retrieved from properties file in loklak

**Comment by prasht63** [comment]
![image](https://cloud.githubusercontent.com/assets/2105062/9193646/90818442-4032-11e5-8fba-58e56b88a902.png)
Start ups now show on the map. 
@mariobehling Do we need to show it as an overlay on the /map or should we have a separate page for startups, /startups

**Comment by mariobehling** [comment]
This should be available through the search UI. What would I have to enter to get this map in search?

**Comment by mariobehling** [comment]
@prasht63 My idea would be to show results in a search view like here https://github.com/loklak/loklak_webclient/issues/454 What do you think? Still wondering what syntax we can use to get the relevant results.

**Comment by prasht63** [comment]
@mariobehling Currently what is shown on map is just a list of start-ups.Maybe we can do something location specific, User can search for "startups+berlin" or maybe "startups:berlin" .I have doubt here, currently I am showing this map on a separate page since oAuth was associated.So should I continue this approach..Currently this map is at localhost:3000/startups

**Comment by mariobehling** [comment]
We need to understand your approach more in detail. 
1. Please list the steps a user can connect his account with angel.co.
2. What data are you specifically importing? 
3. What data is account specific for the user? What data is general information of angel.co?

**Comment by prasht63** [comment]
1.Currently the flow is like
The user clicks on Data Connect --> There Angel.co is present as active source--> User clicks on Angel.co --> Its takes it to login page of Angel.co where he authenticates himslef and gets an access token(basic oAuth step) and is redirected to /startups where he sees startups on the map.

2.As per now Angel.co does not support any personal data api, we can get data about startups.Right now I am just using the access_token to get the startups information(all the startups which are listed on Angel.co so that they can be visualised)

3.No account specific data,other than personal info(nothing else supported by API), general info which is interesting is List of startups which are fundraising, list of startups by location

**Comment by mariobehling** [comment]
1. The Data Connect page has been updated now. Please add Angel.co now.

2. Please tell me, where is this information stored in loklak?

3. How could we use a search syntax to search for specific questions?

4. Please create a table here as an example with all info from Angel.co

**Comment by prasht63** [comment]
1. I am planning to add it to Active Data Source.Something like this
![image](https://cloud.githubusercontent.com/assets/2105062/9234994/bf6b0b70-4159-11e5-94d2-99fa6e2b3787.png)
2.No information is stored in Loklak regarding start-ups because Angel.co API strictly says that API should not be used to clone data from Angel.co [https://angel.co/api/terms]
3.I am thinking something like "berlin : startups" in search box to show start ups in Berlin.
4.From map point of view we have following thingwhich can be showcased on a Map.
1.Startups
2.Jobs (Location wise in startups)

**Comment by mariobehling** [comment]
The import data source wizard does not seem suitable for Angelo.co as it is not a data file or URL.

The API connect is more something similar to an app as it is used in twitter and linkedin. Also the flow is not the same as for the source. Please rather do something like below.

![screenshot from 2015-08-13 01 01 25](https://cloud.githubusercontent.com/assets/1583873/9239327/fb59abea-415a-11e5-9a23-8e9c9d5fab0a.png)

**Comment by prasht63** [comment]
Sure, but I don't see Active Apps category on test.loklak.net/dataConnect.Should I create that section?

**Comment by mariobehling** [comment]
Yes, that is the idea.

The steps you describe are different to the data import steps. Please reflect this in the UI. So, the app import can have its own import UI for now. Something similar to below.

![bf6b0b70-4159-11e5-94d2-99fa6e2b3787](https://cloud.githubusercontent.com/assets/1583873/9244016/6dd27684-4197-11e5-85ba-bcbd0340c435.png)

**Comment by prasht63** [comment]
I am thinking 
![image](https://cloud.githubusercontent.com/assets/2105062/9244101/9f6d76d0-41b5-11e5-9551-87c09b57d1ab.png)
On clicking Add App will open a modal dialog which will have Angel.co API and Instagram(at a later stage).What do you think?

**Comment by mariobehling** [comment]
Yes, that is what I just proposed with this screenshot. Please adjust according to the import process.

![bf6b0b70-4159-11e5-94d2-99fa6e2b3787](https://cloud.githubusercontent.com/assets/1583873/9244016/6dd27684-4197-11e5-85ba-bcbd0340c435.png)

**Comment by mariobehling** [comment]
Another approach is to implement a web crawler rather than using the API. Let's follow up on this here: https://github.com/loklak/loklak_server/issues/346
