### ISSUE TITLE
Top Bar - UI Design Fixes

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#231]
Please fix the 
A) Center "Loklak Logo"
B) Switching between "Home" View and "Map" View shows that to top bar is not aligned identically
C) In different screen sizes and resolutions the top bar behaves differently. See screenshots below
![screenshot from 2015-06-26 17 56 08](https://cloud.githubusercontent.com/assets/1583873/8381622/06887d1e-1c2d-11e5-8323-ecc8496a1eb8.png)

--
![screenshot from 2015-06-26 17 55 51](https://cloud.githubusercontent.com/assets/1583873/8381623/06910286-1c2d-11e5-9b2f-53931ffd8e0f.png)

--
![screenshot from 2015-06-26 17 55 29](https://cloud.githubusercontent.com/assets/1583873/8381624/0694c1a0-1c2d-11e5-8f78-dc20d6137424.png)

**Comment by mariobehling** [comment]
Also please look into the following:
1. ensure 0 px between underline and below area (at the moment there is a white line)
2. Match color of blue with blue color of tweet button
3. Currently the effect to change blue color is delayed. Please make the effect immediate.

![screenshot from 2015-06-26 19 45 12](https://cloud.githubusercontent.com/assets/1583873/8383745/71fb2a88-1c3c-11e5-9723-1629a08d5248.png)

**Comment by mariobehling** [comment]
Where can I test this?

**Comment by sudheesh001** [comment]
@mariobehling point 1 you said for is done, point 2 and 3 are pending, i'll push the patch for point 2 by the end of the day and it'll be visible in todays deployment. It's just that I am unable to figure out where the animations of the change blue effect is coming from. I've cleaned up most of the unused content in the repository. Hopefully this should be fixed soon.

**Comment by mariobehling** [comment]
@sudheesh001 What about the issues I first mentioned? A, B, C?

**Comment by sudheesh001** [comment]
- [x] ensure 0 px between underline and below area (at the moment there is a white line)
- [x]  Match color of blue with blue color of tweet button. (On local, sending a PR)
- [ ] Currently the effect to change blue color is delayed. Please make the effect immediate.

**Comment by mariobehling** [comment]
Did you look at the top of this issue?

[ ] Center "Loklak Logo"
[ ] Switching between "Home" View and "Map" View shows that to top bar is not aligned identically
[ ] In different screen sizes and resolutions the top bar behaves differently

**Comment by sudheesh001** [comment]
@mariobehling For those problems I mentioned something about it in https://github.com/loklak/loklak_webclient/pull/235#issue-91562495

Pasting the same back here.
The main problem I noticed while debugging the designs so far is that the top navigation has another module embedded along with it which is kept as signin-twitter and is being called to load that file, The topnav will have lesser problems if we can integrate the functionality of signin-twitter with that of the same topnav file rather than keeping them seperate.
I could be wrong in breaking something out of a higher modular structure and proposing to put it into a less modular one, what do you think @fuksi ? Would it be possible to merge that file with the topnav file instead of keeping them seperate ?
Your inputs also: @prasht63 @aneeshd16

**Comment by fuksi** [comment]
@sudheesh001, @prasht63, @aneeshd16 
If you checked the html rendered in developer tools, angular directive is rendered as is, nothing is blocking your change in UI. You can do html and css just as you do in others. **Angular is only dealing with the data**. The only blocker is the template HTML. I removed all the old code and create a new navbar. Please in the future, if you want to use template class (navbar, navbar-collaspe), which is of course up to you, but please consider if you can use that all the way, meaning you have total control of the behaviors and stylings to fix this kind of issues.

@mariobehling Back to the top bar, all of this is fixed. Please check live preview in #237, I just updated a link there.

About the angular thing, modular structure was a minor reason here to use a separate directive there. The main reason is to control the flow of one operation: authentication. If `signin-twitter` was not there, you would have to place the login operation somewhere else, says, `on-run.js`, which doesn't make sense of the application structure, nor define the flow of application (e.g. when will authentication run? before what? after what?)

**Comment by mariobehling** [comment]
* [ ] In last version the top bar misses white edges on both sides in map search view.

![screenshot from 2015-07-01 00 31 52](https://cloud.githubusercontent.com/assets/1583873/8443639/b985069a-1f88-11e5-9c91-924d9528a319.png)

**Comment by mariobehling** [comment]
The following views slightly move the top bar
* [ ] search in account view
* [ ] wall view top bar (switch between home and wall and see the top bar moving, why?)

Other
* [ ] tweet button disappears in some resolutions.

(Please click on all fields including in former comments, what is solved)

**Comment by fuksi** [comment]
Noted

**Comment by fuksi** [comment]
VIews slightly moves because of the appearance/disappearance of scrollbar. 

![image](https://cloud.githubusercontent.com/assets/6878677/8462921/a490882e-203f-11e5-856d-c6d0baa35f16.png)

- Search in account view: This I can mimick to prevent the moving top bar because the results are always long enough. This is fixed with PR #259

- Switching between wall - home: For a logged in user, the timeline will be long enough for the scrollbar to appear. Meanwhile wall view is empty as initial so there is no scrollbar. I suggest keeping this, because scrollbar is important to "mark" that "Oh, there are more things, I should scroll down to see". 

- Tweet button disappears: it didn't disappear. It's in the collasped navbar. 
![image](https://cloud.githubusercontent.com/assets/6878677/8463108/db95f6fa-2040-11e5-8e5d-19fb1ca4f85f.png)
![image](https://cloud.githubusercontent.com/assets/6878677/8463114/e6801af0-2040-11e5-82de-135d1837da3c.png)


This is a judgement call that I had to make, because there aren't enough space for everything in mobile. Search box will be there regardless of the data source.Tweet maybe not.

**Comment by mariobehling** [comment]
Please check if the window width is smaller the tweet button disappears indeed. Please also compare the behaviour with twitter in detail with different screen widths. Let's look more at details.

![screenshot from 2015-07-01 21 46 13](https://cloud.githubusercontent.com/assets/1583873/8463465/bbe900e6-203a-11e5-9446-c83ccb782895.png)

**Comment by mariobehling** [comment]
Except for the missing tweet button, let's move the other details to M3. We want to progress with other features as well.

**Comment by fuksi** [comment]
Fix missing tweet button in #259.

**Comment by mariobehling** [comment]
* [ ] Also check not to include the top bar in scroll down (Please compare to twitter and FB)
