### ISSUE TITLE
Develop Map Page as an alternative Home Screen. Show Followers, Following, Tweets of Following on the map

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#232]
http://test.loklak.net/map Please add the following features:
1. Followers on the map (in one color)
2. Following (people) on the map (in another color)
3. Last 100 Tweets of following
4. New tweets pop up automatically (and we keep the last three tweets open. If a new tweet comes up the oldest tweets closes.)

Show an overlay box on the right, where users can show if they display 1-4.

**Comment by mariobehling** [comment]
Just a thought: I would like to see where the followers of Justin Bieber come from. There is usually a location tag in users profile.

**Comment by prasht63** [comment]
am able to get the list of followers from the Twitter using hello.js api however the location in the response is the name of the place.To plot on the map I need the coordinates.I tired using Google Maps API to geocode the location but that's too slow since they put a cap of 5 results per second.Thus we need loklak to provide Geocoding Service.A issue has been created 
Requires https://github.com/loklak/loklak_server/issues/62

**Comment by Orbiter** [comment]
the geocoding servlet is now available. See https://github.com/loklak/loklak_server/issues/62 for details.

**Comment by mariobehling** [comment]
Let's keep this issue open and keep info here to smoothen this feature and implement all details.

**Comment by prasht63** [comment]
Yes

**Comment by mariobehling** [comment]
Let's experiment with the size of the image of followers/following. Can you reduce the size to 30x30 pixel, please?

**Comment by prasht63** [comment]
Implemented with #313
