### ISSUE TITLE
Special characters and emoticons not displaying

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#233]
Special characters don't display correctly.
![screenshot from 2015-06-26 19 32 25](https://cloud.githubusercontent.com/assets/1583873/8383398/23d86304-1c3a-11e5-9d0c-cdc024039279.png)

![screenshot from 2015-06-26 19 32 11](https://cloud.githubusercontent.com/assets/1583873/8383399/240a87ee-1c3a-11e5-97a0-2df15a37bc46.png)

**Comment by fuksi** [comment]
This is not exactly a bug. This is what provided by the server at the moment. For now I can't think of a solution to convert this to an image, because they're also not the original images neither are HTML entities, they are just alternative values (please see `alt` in the screenshot below). 

http://loklak.org/api/search.json?timezoneOffset=-180&q=id%3A614486035557425152

@Orbiter, what is your take on this? Is it possible to also get the html tags inside the tweet text

![image](https://cloud.githubusercontent.com/assets/6878677/8384308/e56b331c-1c48-11e5-850a-c7856288cb2d.png)

**Comment by mariobehling** [comment]
Ok, I understand this about emojis. What about special characters like Apostrophs ('). I see here a "9" shows up for example.

**Comment by Orbiter** [comment]
The 9's are caused by the scraper. Strange. Must debug this.

**Comment by Orbiter** [comment]
I just updated loklak_server with a bugfix for bad decoded characters, including the strange 9-instead-apostroph thing.

**Comment by fuksi** [comment]
Thank you.

**Comment by mariobehling** [comment]
Still seems to appear in user names.

![screenshot from 2015-06-29 12 51 47](https://cloud.githubusercontent.com/assets/1583873/8406538/a7481f8e-1e5d-11e5-8084-786a9d2b5761.png)

![screenshot from 2015-06-29 12 51 28](https://cloud.githubusercontent.com/assets/1583873/8406539/a74e81c6-1e5d-11e5-8819-a692cd93a84c.png)

**Comment by Orbiter** [comment]
I just fixed and deployed a fix for this; however, it applies only on new users scraped after the fix was active.

**Comment by mariobehling** [comment]
Ok, I am closing this then. I am still seeing user's like that. I wonder if it is possible to re-import these user again. @Orbiter I leave it to you then. Cheers!
