### ISSUE TITLE
Implement Top Nav Bar to fit different screen sizes

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#239]
Implement changes for:
* change size of tweet button depending on screen size
* change size of search area depending on screen size
* make text of top bar items disappear and show icons only for small screen sizes.

Compare the behaviour with the twitter top bar:

![screenshot from 2015-06-29 09 32 44](https://cloud.githubusercontent.com/assets/1583873/8403140/19898f72-1e42-11e5-8f24-746c6ed17f8f.png)
--
![screenshot from 2015-06-29 09 33 04](https://cloud.githubusercontent.com/assets/1583873/8403139/1980ff1a-1e42-11e5-89cc-0afdec394544.png)
--
![screenshot from 2015-06-29 09 33 34](https://cloud.githubusercontent.com/assets/1583873/8403138/18ea1672-1e42-11e5-836b-e269cc320ab9.png)
--
Reference previous PR: https://github.com/loklak/loklak_webclient/pull/237

**Comment by fuksi** [comment]
Regarding https://github.com/loklak/loklak_webclient/pull/237#issuecomment-116650242
It's true that most sites have items listed verticaly
![image](https://cloud.githubusercontent.com/assets/6878677/8463239/7e340140-2041-11e5-80a4-bc58fbfb4944.png)

However, our view I suggest keeping the horizontal list for now, because our view's name is very short, until there is a need to have vertical list.

Regarding the breaking to the next line when width is small enough. Of course it'll always break when the screen size is squeeze enough. It was made to work with > 310px & above (meaning even on iPhone 3).

![image](https://cloud.githubusercontent.com/assets/6878677/8463200/48543662-2041-11e5-94e9-ca5260df08ca.png)

**Comment by mariobehling** [comment]
Please compare your solution with the twitter bars on the top as a reference and you will see, that there are a number of improvements necessary before we can close this issue.

**Comment by mariobehling** [comment]
Please also read more carefully the description of the issue and mark for us, what has been implemented:

* [ ] change size of tweet button depending on screen size
* [ ] change size of search area depending on screen size
* [ ] make text of top bar items disappear and show icons only for small screen sizes.

**Comment by fuksi** [comment]
I would have no probs/obstacles implementing the above, however, IMO the contexts are clearly different. 
For a twitter user, it easy to look at these and guess what they are, because they're using twitter!
![image](https://cloud.githubusercontent.com/assets/6878677/8466498/1c12d462-205c-11e5-8caa-b6fb2f73032b.png)
But for a new loklak user, would this be friendly UX? ![image](https://cloud.githubusercontent.com/assets/6878677/8465327/e53710d4-2051-11e5-93ca-7a33b0a0823b.png)

A loklak user would also understand quickly the button `Tweet`, rather than this picture ![image](https://cloud.githubusercontent.com/assets/6878677/8466743/9e106c8e-205e-11e5-9a57-ad6c3bd97b18.png), because it's not in a twitter'user context.

Of course this is just my very subjective opinion about UX. If you insist on the necessary of the changes, please confirm here again!

**Comment by mariobehling** [comment]
Yes, good input. 

1. Please make the smaller version of the tweet button with the twitter bird then. This should be easier to understand. Also a square around the tweet button might be an option. We can experiment this later as well with a designer. For now it is important to have a smaller button as well.

2. Please also make the icons bigger in relation to the text. See how the icons itself are bigger in twitter in relation to the font?

**Comment by mariobehling** [comment]
We also need a button for the top nav bar item "Connect". Here we want to show all services and devices (IoT) that are connected to loklak. What icon could you think of?

**Comment by sudheesh001** [comment]
These look like possible icons for the task in my opinion
http://fontawesome.io/icon/heartbeat/
http://fontawesome.io/icon/puzzle-piece/
http://fontawesome.io/icon/sitemap/
http://fontawesome.io/icon/magic/
http://fontawesome.io/icon/umbrella/
