### ISSUE TITLE
Search end date drop down wont disappear after time is selected .

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_webclient#27]
On http://loklak.net:3001/statistics
A Minor problem.
After selecting end date and time the drop down menu is still there until the search button is clicked.
Change the statistics end date a second time the selection menu wont disappear until you click some where else on the page or the search button.

Would it be a good idea once the date and end time is selected the client goes to a search automatically?

**Comment by Orbiter** [comment]
I support smokinwheels suggestion in part: lets close the selector when the time is selected, but don't search automatically. I believe that would be confusing. But the selector should be closed. Can the search button then be highlighted?

**Comment by sudheesh001** [comment]
Considering the way they're currently behaving, like linked options i.e. Steps as
- Fill the 1st datetime
- Jump automatically to 2nd datetime
- Fill the 2nd datetime

Currently what is happening is
- Repeats the selection of 2nd datetime

It'd be best if the selection is present onto the `Submit` query button so that pressing an `Enter` can do the required job rather than it be closed.

**Comment by Orbiter** [comment]
yes, thats good! Can you please change it that way?
