### ISSUE TITLE
Define Source as Search Parameter

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#290]
As we are adding different data sources and IoT to the search, the question is, if we ad a source parameter to the search. 

The current search with the hashtag #USA for example should display all results from all sources in the system: http://test.loklak.net/search?q=%23USA

How can we define to only show results from the source twitter?

**Comment by fuksi** [comment]
I believe there is a parameter in the query that can help us with that. e.g. `source=twitter` (other options are `cache`, `backend`, `all` as default). Api link: http://loklak.org/api.html. It's hard to demonstrate now since I can't see any other source but `"source_type" : "TWITTER"` in the search result. When there are other sources, I'm sure can create a filter-like option in search to define the source of the search results.

@prasht63, @zyzo I believe there is an integration going from other data sources, can you give us a quick update here?

**Comment by zyzo** [comment]
@fuksi please take a look at PR https://github.com/loklak/loklak_server/pull/79. I believe this is what you're looking for ? 

To search only twitter data, the search query would be `/search?q=%23USA%20%2Fsource_type%3DTWITTER`

**Comment by fuksi** [comment]
@zyzo Thank you, the PR clears this up. Can you prefer to this issue again when the PR is merged. And if possible, a example query that contains results from `source_type=FOSSASIA_API`  as well.

**Comment by fuksi** [comment]
In the meantime, I'll define source = twitter as default
