### ISSUE TITLE
Get location information from browser (share location) and add it to tweet when posting from loklak

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#292]

**Comment by sudheesh001** [comment]
related https://github.com/loklak/loklak_webclient/issues/93

**Comment by mariobehling** [comment]
I never receive any request from the browser to "share the location". I also wonder where you store the IP address. If this issue is really closed. Please document here, where you save the info and how you implemented it.

**Comment by mariobehling** [comment]
Where to test this?

**Comment by mariobehling** [comment]
Location does not show up in UI after location is shared. Feature is not fully implemented.

**Comment by mariobehling** [comment]
Implementation is not thought through and gets in the way of the user.
* [ ] Share location appears even for not logged in users. Currently we dont need this feature for those users.
* [ ] Share location appears on different pages, where it is not needed.
* [ ] It seems like in many cases the browser does not remember after share location was activated.

**Comment by sudheesh001** [comment]
> Share location appears on different pages, where it is not needed.

Since the location is integrated with the tweet functionality and like twitter, a user can open up the tweet box from anywhere during his browsing experience, the share location appears on all pages. This can be fixed using the procedure that users who aren't logged in, need not see this.

>  It seems like in many cases the browser does not remember after share location was activated.

I tested this on both chrome and Firefox, There's a small crosshair picture that appears in the URL bar indicating that the location is already shared. Could you give the test to a particular page where the share location wasn't activated by default ?

**Comment by mariobehling** [comment]
Please only activate "share location" when a user actually pushes the "tweet button" and a tweet field opens.
