### ISSUE TITLE
If Tweets do not have geo-location info, show them from the location of the user account on the map (if account has location info)

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#321]
In the search on the map, currently only tweets with some kind of geolocation info are displayed. If there is not geo info, they are not displayed. A way to increase the number of tweets showing up: If Tweets do not have geo-location info, show them from the location of the user account on the map. Prerequisite is of course, that the account has location info of some sort.

**Comment by fuksi** [comment]
@Orbiter, currently there is no location info in the `user` field in the search result. At the moment I can think of 2 way to proceed with this:
- Check for `place_name`. If has `place_name`, request to the loklak API to convert `place_name` to `lat, lng`
- From user screen_name, get location of the user

I'm guessing that loklak API already storea `lat,lng` related to place name so the first option can be easily implemented from the server, however, it's not an absolute solution since `place_name` field is empty quite often. The second option might requires more scrapings. 

The last option is call directly to twitter API to get/guess the location of a user: https://dev.twitter.com/rest/reference/get/users/show

**Comment by Orbiter** [comment]
The server already should compute location positions from the `place_name`, if this does not happen it's a bug.

Getting the user information with location info is a matter of adding user information to loklak_server at all. Therefore this is related to https://github.com/loklak/loklak_server/issues/64
I am actually working on this right now. I had some successfull testing using the twitter4j api to get user information. Right now I am creating the infrastructure to store the user data.

Therefore, please consider that you may get location information soon attached to the user field or using the account.json servlet.

**Comment by Orbiter** [comment]
Please implement the reading of locations from the server. You can call
`http://localhost:9000/api/account.json?screen_name=<screen_name>` and then you get a `user` object which has a `location_mark` and `location_point` attribute attached, containing the location as `[lon, lat]` values. Please use the `location_mark` value.

**Comment by fuksi** [comment]
Done with #378
