### ISSUE TITLE
no webpages available because http://cdnjs.cloudflare.com unavailable

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#345]
loklak_webclient loads a css file from ```http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css``` which is unavailable right now. Therefore NO weblclient page loads. We should not depend on such resources.

Because such services will kill our online service if they are unavailable, we should integrate the css into our repository instead of loading that from their (unavailable) servers.

**Comment by mariobehling** [comment]
@fuksi Where is the cloudflare dependency documented? Who has got the admin access? I do not remember that we actually decided together to use cloudflare. Any additional info on that?

**Comment by prasht63** [comment]
@fuksi Since this is related to followers map I am taking care of this.Thanks :)

**Comment by fuksi** [comment]
@mariobehling as what it is at the moment, it's not about cloudfare, but it's how we included the library. It should not have been like this. 

@prasht63 Sorry I already took care of it on Saturday, I just forgot to put up the PR :) It's not exactly only about followers map, we have a lot of libraries, those are included in a not so optimized way.

Fixed in https://github.com/loklak/loklak_webclient/pull/350

**Comment by mariobehling** [comment]
@fuksi Nevertheless as this questions comes up, we would like to know now, how does cloudflare end up in the code? Who has made a user account there? Who has access? Where did you document this? Why is it necessary?

**Comment by fuksi** [comment]
@mariobehling, I already removed it in the PR. It was `leaflet` so I guess that @prasht63 included this when he started the map. No one made an account there at Cloudfare. Cloudfare is just what leaflet is using for CDN: http://leafletjs.com/download.html , it could have been any other CDN, like MaxCDN, Azure, etc..

It's a common habit to include libraries with CDN links, so that, said if loklak hosting was in Germany and some one from Brazil wants to access the page, loading the library directly from our files will result in some delay, why through CDN it is faster because the files are distributed somewhere near Brazil.

**Comment by mariobehling** [comment]
Ok, got it. We are using Cloudflare in other projects as well, but free usage is limited and the service should also work without a CDN. Thanks for the clarification!
