### ISSUE TITLE
Twitter previews show up as empty images on loklak search

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#354]
Twitter seems to display previews for links or similar images. When we have a search on loklak these image areas are empty and the image does not show up.

http://test.loklak.net/search?q=Something%20I%20gave%20a%20talk%20on
![screenshot from 2015-07-14 16 04 54](https://cloud.githubusercontent.com/assets/1583873/8675138/831bd8b2-2a42-11e5-865f-c7081c7dcaca.png)

https://twitter.com/elioqoshi/status/620930773596696576
![screenshot from 2015-07-14 16 06 41](https://cloud.githubusercontent.com/assets/1583873/8675141/86adf852-2a42-11e5-9265-adc8196c943f.png)

**Comment by fuksi** [comment]
This bug is bigger than it seems.
- Here the result from local service http://gofullstack.me:8061/oembed?url=http://buff.ly/1De2NqH , which return the wrong thumbnail url
- And from the iframely home page  http://iframe.ly/Ix8ga6.oembed , which is much more sophisticated.

I alread tried update the repo but apparently, the version https://github.com/itteco/iframely/tree/master is still dated from June. I guess they limits the open source version for some advantages.

Anyway, I'll find another way.

**Comment by mariobehling** [comment]
Do you have a screenshot? Is the solution not to show the image?

**Comment by fuksi** [comment]
The solution is to change and engine to get embed code. The solution was merged. The deployment was slow today. I just deployed again. Let's try the same link again 

http://test.loklak.net/search?q=%23mozweekend

**Comment by mariobehling** [comment]
Not getting any result on the link given at the moment.

![screenshot from 2015-07-17 16 28 03](https://cloud.githubusercontent.com/assets/1583873/8749271/df53f50a-2ca0-11e5-9544-bb8546b548e3.png)

**Comment by fuksi** [comment]
Apparently loklak server was down for a while. You can try again now: http://test.loklak.net/search?q=%23mozweekend
