### ISSUE TITLE
Search breaks when search encounters json with special characters

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#372]
`Uncaught SyntaxError: Unexpected token ILLEGAL`
```
search.json?callback=angular.callbacks._0&q=%23loklak:147 Uncaught SyntaxError: Unexpected token ILLEGAL
```
Error flagged at : 
```
    "text" : "#loklak will provide 'rich tweets' with long texts after a *** and then *markdown* is supported for more than `140` chars. (this is a test)",
```
Sample present in response is
```
{
    "created_at" : "2015-07-13T15:08:37.000Z",
    "screen_name" : "loklak_messages",
    "text" : "#loklak will provide 'rich tweets' with long texts after a *** and then *markdown* is supported for more than `140` chars. (this is a test)",
    "link" : "https://twitter.com/loklak_messages/status/620610789171400705",
    "id_str" : "620610789171400705",
    "source_type" : "TWITTER",
    "provider_type" : "REMOTE",
    "provider_hash" : "7fffffff",
    "retweet_count" : 0,
    "favourites_coun
```

**Comment by fuksi** [comment]
I believe the cache is already updated. You won't be seeing this status anymore. This was a test and unfortunately it contains non white space character. 

About the error: If you copy and paste that `a***and` to the text editor and inspect it, you can see the illegal token. Our application won't be able to parse this since the protocol is JSONP & callback=angular, which will treat this whole JSON as javascript object, hence the illegal token.
