### ISSUE TITLE
Some profile pictures on search query throw 404 errors

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#42]
An example URL is as follows
`https://pbs.twimg.com/profile_images/586512026672893954/WNMdBaR0_bigger.jpg`

Even when separately opened, the browsers shows a broken image, but on the same tab, the favicon shows the 16x16 version of the profile image.

![screen shot 2015-05-10 at 4 25 15 pm](https://cloud.githubusercontent.com/assets/4545925/7554411/3607e1c2-f731-11e4-87d9-d7b21fad131a.png)

**Comment by julianfox** [comment]
+1

**Comment by Orbiter** [comment]
I can open the image you gave without problem. Even the larger version with url
https://pbs.twimg.com/profile_images/586512026672893954/WNMdBaR0_200x200.jpg
can be loaded.

**Comment by julianfox** [comment]
I can open this one, but i have a lot of 404 errors when i use the search

**Comment by sudheesh001** [comment]
I can open the images after a long time on the same browser and immediately after hitting a 404 on a different browser. Looks like they have something which denies us from loading so many images. What is the workaround ?

**Comment by Orbiter** [comment]
caching at the server can help, but loading only through the server won't do because then the server gets the attention from twitter which will cause a blocking of the server.

What we need is a caching at the server while that server never loads the images. The client (the browser!) would need to send loaded images back to the server so the server can provide that cache to the next client.

Additionally every browser/client must load from the server if the direct loading from twitter failed.

Can this be done on the client side, considering a cache at the server would exist?

**Comment by Orbiter** [comment]
I believe we must work around this problem since I suspect that twitter rejects access to the images.
The solution is proposed in https://github.com/loklak/loklak_webclient/issues/59
Since there is no actual software error here, I close the issue.
