### ISSUE TITLE
Map: Click on user tweet in activity feed does not show location

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#430]
Even though the user is listed on the site, it does not show up on the map.
![screenshot from 2015-08-04 14 40 29](https://cloud.githubusercontent.com/assets/1583873/9060761/1539dff8-3ab7-11e5-9664-a605a871d6e5.png)

**Comment by mariobehling** [comment]
The question here is also, do we want the tweet to appear in the location of the user or do we want the tweet to use its own location - the tweet location.

**Comment by fuksi** [comment]
The feeds are coming from Twitter API (loklak is not supported yet). The tweet itself does not have a location. The way it works at the moment is
1. Click on a feed => check the user of that feed
2. Find that user on the map
3. Open the popup

So if sth failed, that would be on step 2. The most stable way to solve this is that: all results from e.g. 
http://localhost:9000/api/user.json?screen_name=phucdn2005&following=100, must have geojson included. I recognize sth that can be enhanced from the server. https://github.com/loklak/loklak_server/issues/107 . The client will be enhanced automatically when the issue is done.

About the original issue. My bad, for testing I set a limit of 500 for followings/followers. Now it's 10000. Patched in #435
