### ISSUE TITLE
Leaderboard upgrade including three column layout and top mentions

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#436]
* [ ] Increase number of top twitterer etc. to six and adapt the design accordingly
* [ ] Change to a three column leaderboard layout and include Top mentioned
* [ ] Propose a way to deal with long hashtags, that do not currently fit into the design
* [x] Look into faster loading leaderboard options

**Comment by aneeshd16** [comment]
My solution to this: Instead of keeping a fixed number on the leaderboard, let it be defined by the screen size. The histogram would always stick to the bottom of the page, and the number of leaderboard items will depend on how much space is available above the histogram. For example:
**Still in progress**
1366x768
![image](https://cloud.githubusercontent.com/assets/5436027/9427214/30876f92-498e-11e5-93cb-4cad7d90fea5.png)
1920x1080
![image](https://cloud.githubusercontent.com/assets/5436027/9427217/492f942a-498e-11e5-8468-bb10bebe716d.png)

**Comment by mariobehling** [comment]
Good idea! Thank you.

**Comment by aneeshd16** [comment]
1366x768 (regular view)
![image](https://cloud.githubusercontent.com/assets/5436027/9446735/d06d61b0-4ab0-11e5-8ef1-924757d53c22.png)
1366x768 (full screen)
![image](https://cloud.githubusercontent.com/assets/5436027/9446750/e2435b9c-4ab0-11e5-829d-4080ede61f15.png)
1920x1080
![image](https://cloud.githubusercontent.com/assets/5436027/9446923/1ba5e912-4ab2-11e5-8449-375b33bc47f2.png)

The bar chart occupies 25% of the screen height and sticks to the bottom. The leaderboard items are overlapped by the chart. To make the transition seem smooth, I added a gradient from (transparent->background color of wall). 
Alternatively, I can add code that detects the parts that are overlapped by the chart and hide them completely. However, I guess the overhead too detect the bounding rectangles of all leaderboard items and checking if they are being overlapped will be quite high.

**Comment by mariobehling** [comment]
Looks all good for me. Please proceed.
