### ISSUE TITLE
Use same CSS and font sizes for "trends sidebar" on search page as on home page

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#458]
* [x] use same CSS for all sidebars
* [x] use same font and font size
* [x] use same colors for all sidebars

![screenshot from 2015-08-12 00 00 50](https://cloud.githubusercontent.com/assets/1583873/9211958/ad5ca576-4085-11e5-8dbf-211a60fcd9f0.png)

**Comment by fuksi** [comment]
The background color of the trends are different between home view & search view in twitter (one is white and one is nothing/grey). I'm guessing that in seaching, they want to implement the search result in search view.

**Comment by mariobehling** [comment]
Background color should be white on all sidebars. Heading design should be like in the first screenshot. Please make the heading like in the twitter design. See below.
![screenshot from 2015-08-12 12 54 05](https://cloud.githubusercontent.com/assets/1583873/9222343/65defcd2-40f1-11e5-9325-afa789663c5e.png)

**Comment by mariobehling** [comment]
> I'm guessing that in seaching, they want to implement the search result in search view. 

Who is they? Search is your project! When it is written all design bars should be the same design, I am confused you are asking more. What is unclear here? It does not work if everyone implements different designs on each page. We need a common feel and flow.

**Comment by fuksi** [comment]
Sorry I missused a word there, it should be
> I'm guessing that in seaching, they want to **emphasize** the search result in search view. 

By they, I meant Twitter. The difference I mentioned is between: https://twitter.com/ (logged in) & https://twitter.com/search?q=%23vow&src=typd. Please notice the background-color in the screenshots below.

![image](https://cloud.githubusercontent.com/assets/6878677/9222452/8c2435b6-40fa-11e5-8332-e2306a5a1e2c.png)

![image](https://cloud.githubusercontent.com/assets/6878677/9222462/a1cda01e-40fa-11e5-9f20-251f23462701.png)

I'm confused because it's twitter design that background colors are different, and the reason for example (I guess) is mentioned in the quote above. So if it's all white, it's not like twitter.

This is a very simple fix. It shouldn't take much of our time like this :) I just want to inform about the twitter design, so please comment quickly if 
- Use same background color for the common feel
- Use different background color like twitter (the current state on live) for emphasis on search result.

**Comment by mariobehling** [comment]
> Use same background color for the common feel

Yes

**Comment by fuksi** [comment]
Fixed. Can be tested on live (might need a refresh)

https://github.com/loklak/loklak_webclient/commit/ee3b4d9fa6ce7e4ac11fe2322e6c3f65c5eaaea3
