### ISSUE TITLE
Data: Public and Private Option and Settings

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#503]
Public/Private: We only need this option, if we require authentication from a user. 

* Public - everything that is public on the Internet should be public. 
* Private - this option can only be used when we add apps, that require user specific authentication. 

Prashant is working on adding apps that require authentication. If a user shares data that requires authentication, the user should stay in control of the data. That means, we can temporally keep the data in loklak, but if the user deletes it from his/her account, others should neither be able to see it.

Follow up to https://github.com/loklak/loklak_webclient/pull/502#issuecomment-132975310

**Comment by zyzo** [comment]
Mail discussions concerning public/private data : 

@zyzo:

The use case of private data is different from public data in several ways : the user that imports the data, is in control of the data. That means only that user is allowed to update/delete, allow/prohibit other people from seeing the data. In order to implement these criterias, I believe following code additions are needed :
1. Add new privacy_status field to MessageEntry, that could be PUBLIC or PRIVATE (PrivacyStatus class is implemented in ImportProfileEntry)
2. Add visibility boolean field value to MessageEntry. For public data this field is of no use. For private data (privacy_status == PRIVATE), if visibility is set to true, other people can search for the data. Otherwise, only the owner can see the data. (this field can also be created as an enum, for extensibility reason).
3. Change the message search method in QueryEntry to match these constraints.
As you have a more global view of loklak_server codebase, do you think these changes are appropriate ?

@Orbiter:

I don't know why we need that, but the proposed solution is not flexible enough. This should be solved using a mandant model where each mandant can apply their access right. This enables that once created record can change their access right without actually changing the content of the records itself. The requiremennts would be simple:

add a field 'collection' with empty default value
each mandat has a name which is written to the mandant value
each mandant can write an access right attribute to a new data structure. This should define access rights to groups 'all', 'group' and 'user' (like in unix groups)
each user of the search interface must be identified to be member of none, one or several mandants. This must be trannslated to a filter query to the collection field.

**Comment by Orbiter** [comment]
The content of the `collection` field would not directly denote that a message is either private or public. It would refer to a profile where the profile owner can set the private or public status.

So by default the field `collection`should be empty or NULL to show that there is no collection assigned; such messages should be public.

Then a user should be able to set a collection metadata with a collection name and the collection access status. For each new message  which the user creates, the collection name should be set into the message field `collection`. The search api must then evaluate that value according to the user`s settings of the collection.
