### ISSUE TITLE
Account Search: Fix bugs and Implement Load on Scroll

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#505]
Apart from 
* [x] missing links to accounts
* [x] missing header images and 
* [x] sometimes missing user account images

please also implement
* [x] load on scroll instead of loading all search results right away.

**Comment by fuksi** [comment]
About load on scroll, I'll implement it, although here's some related info about this feature
- This type of filter is not supported by loklak server at the moment, meaning that I took a normal search and gathered all the user screen_name
- Then I made a new request to the user servlet for more information about those users

=> the number of result is rather limited. I tried get 500  normal search results, so that I can get more different users from that, however the client couldn't handle that much data smoothly. 200 was the optimal choice.

Apparently, twitter is "kind of" doing the same (if you scroll down sometimes it will end, that should not be right, there are absolute more people tweeting the word `hello` than those) https://twitter.com/search?f=users&vertical=default&q=hello&src=typd

**Comment by mariobehling** [comment]
Ok, thanks got it. Should this solution stay or do you suggest to find another solution with loklak server? Also, I see that twitter sorts the accounts according to most relevant on top e.g. with the search term in the user name or user screen name. What is your idea here?

**Comment by fuksi** [comment]
Done with the PR above.  
About enhancement, like sorting for example, the current data from search.json won't suffice from 100 search results, I could find out who tweeted about a term the most and do some sorting, but then how about the next 100 search results, and so on.  

Other than above, I can't find another temporary solution on the client. So in my opinion support from the server for account search is necessary.

**Comment by mariobehling** [comment]
Thank you. 

@fuksi Please open an issue for this feature on loklak_server.
