### ISSUE TITLE
Search results not showing up

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#506]
Please use any keyword and click back and forth through all options (live, accounts, photos, videos) of search. Currently results are regularly missing.

![screenshot from 2015-08-20 20 43 45](https://cloud.githubusercontent.com/assets/1583873/9392311/47c77968-477c-11e5-96d1-e0d9479189da.png)

**Comment by fuksi** [comment]
This happened when the loklak server was down for a while.
Although, if you switch filter fast enough and contiuously, the application will be blocked from loklak server due to high frequency of requests.
![image](https://cloud.githubusercontent.com/assets/6878677/9489737/e51521fc-4beb-11e5-8413-52188717f053.png)

While we can hope for the users to be sane, I'm proposing to disable filters bar (greyed out), when a filter search is still running

**Comment by mariobehling** [comment]
Which area is "filters bar" exactly?

**Comment by fuksi** [comment]
This is the filters bar
![image](https://cloud.githubusercontent.com/assets/6878677/9490262/6d31e19e-4bef-11e5-800c-aedf9930d6a5.png)

When a search is running, it can be shown like this (and the functionality of course must be disabled temporarily until the search is done).
![image](https://cloud.githubusercontent.com/assets/6878677/9490285/89a33152-4bef-11e5-90da-33de7e55c211.png)

**Comment by mariobehling** [comment]
Ok, got it. To disable seems a different user experience to what people are used to at twitter, google..

> While we can hope for the users to be sane, I'm proposing to disable filters bar (greyed out), when a filter search is still running 

It the user starts a new search or changes the filter, how could the current request just be canceled and the new requests be performed.

If as a user I want to look at another search, that my current search, - currently I have to wait until the first search is finished, right? This is not very user friendly.

**Comment by mariobehling** [comment]
Would it be an option to define the loklak webclient as a priority client and allow more requests to the server? Maybe we could introduce authentication of clients and increase the number of allowed requests for authenticated web clients to loklak.org server?

**Comment by fuksi** [comment]
Says my ip is `4.5.6.7`
- When I open `loklak.net` in my browser
- And then do a search 
- The loklak server will address me as `4.5.6.7`, not loklak.net
So if we define a priority for the client, that would apply for all client, and it doesn't even have to be the loklak_webclient we build, and that increases even more risk in DDos:ing to loklak server. So I don't think that this is option  

The problem wasn't about how many requests are allowed, the problem lies in how fast we can request continuously. Maybe @Orbiter can clarify later how tight the DDos setting is, however, one general solution is the raise the concurrent limit of a certain ip:
  - Before, 1 request at a point of time, if more, block for a while
  - After, 5 (or more) at a point of time, if more, block for even longer

Should I follow with the grey out solution for now, or should we wait for Michael's input as well?

**Comment by mariobehling** [comment]
Greying out is not an option. It does not happen on other services and contradicts what users experience elsewhere. Twitter allows certain clients of companies that pay them to perform more requests. We have a different architecture. 

* Nevertheless, what could be a way to distinguish requests from loklak.net or other clients to loklak.org? Client authentication, limit IPs?

* Are there ways to cancel current requests and start new ones? How is twitter doing it? Just by adding computing power?

**Comment by fuksi** [comment]
Twitter is avoiding it by refreshing the page:
- Starting from https://twitter.com/search?vertical=default&q=%23vow&src=typd
- This is what happenned in console when I clicked continously on photos filter:
![image](https://cloud.githubusercontent.com/assets/6878677/9493835/17cebf58-4c0b-11e5-9fc0-23d40980af34.png)

- After this the page is refreshed instantly

**Comment by mariobehling** [comment]
What do we need to implement a similar solution?

**Comment by fuksi** [comment]
This is solely logic from the client side, so we don't need anything to implement this. I have thought of this before, however in my opinion, refresh is always the last resource. 

But in this case, this is suitable because:
   - it works
   - & loklak server can still maintain tight DDos settings. 
   - user experience is not affected much by refreshing since this is a relatively rare case.

I'll implement it this way then.

**Comment by fuksi** [comment]
Solved with PR above
