### ISSUE TITLE
Plugin accounts to loklak

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#511]
In the first phase we implemented loklak as a client for twitter. However the idea of loklak is to allow users to plugin other twitter like services as well, e.g. weibo, or to plugin photo streams into the timeline e.g. flickr.

### USER NAMES and ACCOUNT URLS
So, we need to make some decisions how to display data, specifically in the URL. For example loklak.net/twitterusername to display profile info does not make sense, if one accounts wants to connect to a weibo account, that by chance has the same username and would mean we get loklak.net/weibousername is the same as loklak.net/twitterusername. However, if account holders are different we have a problem.

### Therefore, I propose we implement:
a) loklak.net/loklakusername which can connect with
b) any twitter account, that shows up under loklak.net/t/twitterusername
c) any weibo account, that shows up under loklak.net/w/weibousername
d) other useraccount e.g. flickr /f/flickrusername, fb/facebookusername etc.

### Open questions:
* What happens if a user wants to disconnect his/her twitter account from the loklak account?
* What happens if a user deletes or changes an account name on twitter?

**Comment by fuksi** [comment]
I don't know about the current status of user implementation. I believe @aneeshd16 can give some more info about it here. Anyway here are my thoughts

If we want to converge different accounts from a user, we'll need a loklak user base (hence the user implementation above). Assuming the user base is implemented:  
-  What happens if a user wants to disconnect his/her twitter account from the loklak account?
   - He/she can. We can hold a table of the services a loklak account of connected to. If the user wants to disconnect, simply disable that service along with deleting related data( or keep it). 
-  What happens if a user deletes or changes an account name on twitter?
   - When a user sign in with twitter, we receive access tokens (I believe it's similar to other service as well). So we user delete/change the account name on twitter, we still have the tokens. A notice can be made to the user if the tokens are not any more valid.

**Comment by sopu** [comment]
As already commented by @fuksi , It will require a user base and a potential loklak login as well (if required). 
I agree on the fact that loklak can act as the common site for different social media services. 
I think the open questions have been aptly answered.
