### ISSUE TITLE
Empty areas showing up while generating report

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#512]
Confusing for the user is, that empty areas still show up while the /report is being generated
* [ ] left hand side shows up until report is available

![screenshot from 2015-08-22 10 27 04](https://cloud.githubusercontent.com/assets/1583873/9423154/c30b1778-48b8-11e5-9197-73073b9ded17.png)

* [ ] empty right hand side shows up very briefly and is then hidden. The user wonders "what is it". 
![screenshot from 2015-08-19 11 51 49](https://cloud.githubusercontent.com/assets/1583873/9423156/dc72f50a-48b8-11e5-9377-ac4351d5eeb1.png)

**Comment by prasht63** [comment]
@mariobehling This happens because the charts can't be drawn in a hidden div. Issue link [ https://github.com/jtblin/angular-chart.js/issues/29 ].I was also facing this.A workaround is that I render the charts in hidden div but in that case it flags a error in console and sometimes affects the workflow
Its a small fix, I will send a commit soon for this.
