### ISSUE TITLE
Show number of newer tweets in timeline just as in search

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#515]
After the initial search, the number of newer tweets is shown on the top. 
* [x] Please implement the same feature - show number of newer tweets - for the timeline.
* [x] Please automatically update the times of the tweet, e.g. currently the tweets always show the time when they were loaded.

![screenshot from 2015-08-22 19 28 03](https://cloud.githubusercontent.com/assets/1583873/9425088/011f67f8-4904-11e5-927d-a86ebedde4c2.png)

**Comment by fuksi** [comment]
I watched twitter timeline to see how often the page is updated. The interval is 10secs. Since we're not twitter & we're using their API, I'll implement an interval of 20s, to prevent possible blocking from twitter for too many requests/hour.

**Comment by mariobehling** [comment]
Which specific calls / how many are you making in a 15 minute frame? Please compare to https://dev.twitter.com/rest/public/rate-limiting or https://dev.twitter.com/rest/public/rate-limiting. Which limits are relevant to us here?

**Comment by fuksi** [comment]
I believe this is the one
>GET and POST Request Limits
Rate limits on “reads” from the system are defined on a per user and per application basis, while rate limits on writes into the system are defined solely at the user level. In other words, for reading rate limits consider the following scenario:

>If user A launches application Z, and app Z makes 10 calls to user A’s mention timeline in a 15 minute window, then app Z has 5 calls left to make for that window
Then user A launches application X, and app X calls user A’s mention timeline 3 times, then app X has 12 calls left for that window

I tried 30s period today. It was approximately 10-12 successful times of getting feed until it is blocked. (in order to continue developing, I had to wait for half an hour, or just create a new account...) So the limit above is true. It's only 12 intervals until blocked because we already 2 in the begining to get user data & feed.

I have a temporary solution for this, it sounds desperated but this is only thing I have until further support from loklak server. What if the interval is incremental, so that 12 intervals would fit into 15mins?

If the base interval is 20 secs, the increments is 11 secs, then the time needed for 12 intervals is:
`20 + (20+11) + (20+11+11) + ..... = 955 secs > 15 mins`, then we're safe

The user experience is slightly afffected, but this way we'll make sure the user won't be blocked, says, if he opened the page and left it there for a while to get tea to enjoy loklak the rightway.

**Comment by sudheesh001** [comment]
This long polling procedure is really good. :+1:

**Comment by mariobehling** [comment]
@fuksi Yes, sounds good. In my opinion actually the exact timing is not so important. Important is, that we have this feature at all and that we see newer tweets posted on top at some point. Cheers!

**Comment by fuksi** [comment]
Done with the PR above
