### ISSUE TITLE
loklak search page: identical to twitter search result

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#60]
Please visit http://search.twitter.com and do a search. The loklak search result page must look exactly like that result page

**Comment by sudheesh001** [comment]
Can I assign this to myself ? @fuksi already has quite a lot of work to do, it'd be nicer to share the load :smile:

**Comment by Orbiter** [comment]
This is the umbrella feature for the plan in https://github.com/loklak/loklak_webclient/issues/61

It is honorable that you step in for @fuksi to share the load and it shows also how good you work as a team-member! ..but we would like to separate tasks for each of you: the separation and also the scrum reports will make it transparent how the personal load is.

**Comment by Orbiter** [comment]
please add feature requests to loklak_server if you need them for this feature (I believe we need that for people search)

**Comment by mariobehling** [comment]
Create a list of features and add information about technology and milestones. Please include the following:

a) Feature List (add it to Feature.md)
b) Project Plan with possible milestones (Which features will be implemented at what time)
c) Technologies used

Proposed Milestones

    Milestone 1, Due by June 10, 2015
    Milestone 2, Due by June 26, 2015
    Milestone 3, Due by July 25, 2015
    Milestone 4, Due by August 21, 2015

**Comment by fuksi** [comment]
Features and tasks : 

Layout from to #60 and integrated with AdminLTE.

Detail requirement (**X is done**):

### MILESTONE 1 TARGET: able to render all available kinds of tweet. 

1. Normal tweets without links or pictures
 + Avatar, Screen_name, tweet's age **X**
 + Onclick: show created time, full date, and Detail (to open tweetlink) **X**
 + Action list: Reply, Retweet, Favorite, More (Copy link, Embed tweet) **X**

2. Tweet with images:
 + For a single image, if size is bigger than 506 x 203 create a thumbnail of 506 x 203 **X**
 + With multiple images, create multiple thumbnail baseds on the size of the images
 since maximum no of images is 4. Size of compilation would be 506 x 203. The layout according to twitter search should be
      - For 2 images: 50 50
      - For 3 images: 50 | 25 / 25
      - FOr 4 images: 25 / 25 | 25 / 25

 + Regardless the number of images, there's always a view photo action
     - If a thumbail for a single image was shown before, show the rest of the photo
     - If multiple thumbnails was used, show more detail like normal tweets
     - After view photo is click, a click on images result in a modal.  

3. Tweet with videos:
 + Show link at first, load video as tweets are in focus
 + If video is tweet video, use iframe with given source in loklak result
 + Else:
  - Show logo, source of video (Youtube, Vimeo, Fp, etc..)
  - Request for embeded url of a html5-video-container 

4. Tweet with links:
 + Link is shortenned, by e.g., bit.ly, and already included in the tweet text
 + Debug the link (like Facebook Debugger) to get appropriate thumbnail and description
 + Remove link in text if debuggable.

### MILESTONE 2 TARGET: 
Enable live view (a.k.a tweets wall), implement all available filters & advanced search, integrate with main project's AdminLTE theme.

### MILESTONE 3 TARGET: 

integrate with avaiable twitter services (which should be finished at this time from other projects) such as post tweet, reply, fav, retweet, share, export..

### MILESTONE 4 TARGET:

create logic to render arbitrary results based on Twitter Search, 'Top' filter. 
(I haven't able still, to identify the pattern Twitter use in that view)
