### ISSUE TITLE
Modify gulp configuration to start a node server

### ISSUE THREAD

**Issue by aneeshd16** [loklak/loklak_webclient#81]
Also restart the server when any server file changes

**Comment by sudheesh001** [comment]
@aneeshd16 This looks good, the gulp node is now working perfectly, I think the best thing to do as of now is to remove the keys that you've committed with the application. I think we should parse that for later, but as of now this goes well. I am launching a PR and the review is a conditional `r+` here from me because this is the barebone which will anyway undergo changes

**Comment by aneeshd16** [comment]
The auth part will be done in #80, which also includes moving the keys to the configuration file.
